name: Generate Datas
on:
  schedule: 
    - cron: "0 */12 * * *" # executa a cada 12h
  workflow_dispatch:

jobs:
  build:
    name: Atualizar animação do Snake
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Fazer checkout do repositório
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # importante para usar PAT no push

      # 2️⃣ Gerar o SVG do Snake
      - uses: Platane/snk@v1.1.2
        id: snake-gif
        with:
          github_user_name: MateusDalagnol
          svg_out_path: dist/github-contribution-grid-snake.svg

      # 3️⃣ Debug: verificar se o arquivo foi criado
      - run: ls -R dist

      # 4️⃣ Configurar Git para usar PAT
      - name: Configurar Git com PAT
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      # 5️⃣ Commit e push para o branch output
      - name: Commit e Push
        run: |
          git fetch origin output || git checkout --orphan output
          git checkout output || git checkout --orphan output
          git rm -rf .
          cp -r dist/* .
          git add .
          git commit -m "Atualiza animação do Snake [Automático]" || echo "Nada para commitar"
          git push origin output --force
